import '../globals.css';

import { ThemeProvider } from '@/components/theme-provider';
import Header from '@/components/Header';
import { SidebarProvider, SidebarTrigger } from '@/components/ui/sidebar';
import { AppSidebar } from '@/components/sidebar';
import { Suspense } from 'react';
import Loading from './Loading';
import Footer from '@/components/Footer';

export const metadata = {
  title: 'Renz - Software Engineer',
  description: 'Generated by Next + Sanity',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
 

  return (
    <html lang="en">
      <body className="bg-zinc-100 h-full w-full dark:bg-slate-900">
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Header />
          <SidebarProvider>
            <AppSidebar />
            {/* Ensure the button is rendered consistently */}

              <SidebarTrigger className='fixed bottom-5 right-5 text-4xl rounded-full p-5 border border-gray-800 bg-slate-900 dark:bg-zinc-50 dark:text-slate-900 text-zinc-50 md:hidden z-20 '/>
    
          </SidebarProvider>
          <main>
            <Suspense fallback ={<Loading/>}>
              {children}
            </Suspense>
          </main>
          <Footer/>
        </ThemeProvider>
      </body>
    </html>
  );
}
